config/routes.rb
Rails.application.routes.draw do
  resources :homes
  get 'create', to: 'cards#new'
  get 'mycards', to: 'cards#mycards'
  get 'admincards', to: 'cards#admincards'
  get 'alluserscards', to: 'cards#alluserscards'

  get 'login', to: 'homes#login'
  
  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap

  devise_for :admins
  resources :cards do
    resources :tweets do
      get "delete"
      member do
        put "like" => "tweets#upvote"
        put "unlike" => "tweets#downvote"
      end
    end
  end
  get '/users/auth/:provider/callback', to: 'sessions#create'
  get "users/sign_out" => "sessions#destroy", :as => :signout  
  devise_for :users
  resources :tweets
  root to: "homes#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	belongs_to :card

	validates :user_id, :body, presence: true
	
	before_create :post_to_twitter

	acts_as_votable
	
	def post_to_twitter
		# user.twitter.update(body)
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # before_action :authenticate_user!, only: [:upvote, :downvote]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:index, :delete]

  respond_to :html

  def index
    @tweets = Tweet.all
    if user_signed_in?
      @tweet = current_user.tweets.find_by(params[:name])
    end
    respond_with(@tweets)
  end

  def show
    
  end

  def new
    redirect_to root_path, notice: 'No such url'
  end

  def edit
    @tweet = current_user.tweets.find_by(params[:id])
  end

  def create
    @card = Card.friendly.find(params[:card_id])
    @tweet = @card.tweets.create(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.save
    respond_with(@card)
  end

  def update
    @card = @tweet.card.id
    if @tweet.update(tweet_params)
      redirect_to card_path(@card)
    end
  end

  def delete
    @card = Card.friendly.find(params[:card_id])
    @tweet = Tweet.find(params[:tweet_id])
  end

  def destroy
    card_number = @tweet.card.id
    @card = Card.friendly.find(card_number)
    @tweets = @card.tweets.all
    tweet_user_id = @tweet.user_id
    @tweet.destroy
    # redirect_to @card
    # if current_user.admin == false
    #   respond_with(@card)
    # end
    if current_user.admin == false and tweet_user_id == current_user.id
      respond_with(@card)
    end
  end

  def upvote
    @card = Card.friendly.find(params[:card_id])
    @tweet.upvote_from current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @tweet.get_upvotes.size } }
    end
  end

  def downvote
    @card = Card.friendly.find(params[:card_id])
    @tweet.downvote_from current_user
    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @tweet.get_downvotes.size } }
    end
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:user_id, :body)
    end

    def correct_user
      card_id = @tweet.card.id
      @card = Card.friendly.find(card_id)

      if user_signed_in?
        if current_user.try(:admin?) or current_user.id == @card.user_id.to_f
          @tweet = Tweet.find(params[:id])
        else
          @tweet = current_user.tweets.find_by(id: params[:id])
          redirect_to card_path(@card), notice: 'Can\'t touch this. Not yours.' if @tweet.nil?
        end
      else
        redirect_to root_path, notice: 'Please log in first'
      end
    end

    def is_admin?
      @card = Card.friendly.find(params[:card_id])
      redirect_to root_path, notice: 'You\'re not authorised to do so' unless current_user.admin or current_user.id == @card.user_id.to_f
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Confirm?</h3>
    </div>

    <div class="modal-footer">
      <%= link_to "Yes, Delete This Tweet", @tweet, method: :delete, remote: true, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_save.js.erb
$(".product-index").html("<%= escape_javascript(render 'tweets') %>").masonry({
    itemSelector: '.box'
  })
$("#product-modal").modal("hide")

app/views/tweets/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-body">
      
      <div class="testimonial box-shadow box">
        <% if current_user.admin? %>
          <p>Tweet: <%= @tweet.id %></p>
        <% end %>
        <div class="display-pic">
          <%= link_to image_tag(@tweet.user.profile_image), @tweet.user.url, target: "_blank" %>
        </div>
        <div class="testimonee" style="box-shadow:none;">
          <blockquote>
            <p class="quote-text tweet-body"><%= @tweet.body %></p>
            <% if @tweet.user.provider == 'twitter' %>
              <p class="quote-source"><i class="fa fa-twitter fa-twitter-blue"></i> <%= link_to @tweet.user.name + '@' + @tweet.user.nickname, @tweet.user.url, target: "_blank" %></a></p>
            <% elsif @tweet.user.provider == 'facebook' %>
              <p class="quote-source"><i class="fa fa-facebook fa-facebook-blue"></i> <a href="https://www.facebook.com/<%= @tweet.user.url %>" target="_blank"><%= @tweet.user.name %></a></p>
            <% end %>
          </blockquote>
          <p class="date"><%= @tweet.created_at.strftime("%b %d, %Y") %></p>
        </div>
        <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-message-submit' %>
        <button type="button" class="btn btn-white" data-dismiss="modal">Close</button><p><%= @card_number %></p>
      </div>

    </div>
  </div>
</div>

app/views/tweets/_tweets.html.erb
<!-- Testimonial -->
<div id="tweets">
  <% @tweets.each do |tweet| %>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 testimonial box-shadow box">
      <% if tweet.user %>
        <div class="display-pic">
          <% if tweet.user.provider == 'twitter' %>
            <%= link_to image_tag(tweet.user.profile_image), tweet.user.url, target: "_blank" %>
          <% elsif tweet.user.provider == 'facebook' %>
            <%= link_to image_tag(tweet.user.profile_image), "https://www.facebook.com/" + tweet.user.url, target: "_blank" %>
          <% end %>
        </div>
      <% end %>

<!--       <div class="photo">

      </div> -->

      <div class="testimonee">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <div class="actions topcorner">
              <p>
                <%= link_to 'X', card_tweet_delete_path(@card, tweet), remote: true %> |
                <%= link_to 'O', card_tweet_path(@card,tweet), remote: true %>
              </p>
            </div>
          <% end %>
          <% if current_user.admin? == false and current_user.id == @card.user_id.to_f %>
            <% if tweet.user_id != current_user.id %>
              <div class="actions topcorner">
                <p>
                  <%= link_to 'X', card_tweet_delete_path(@card, tweet), remote: true %>
                </p>
              </div>
            <% end %>
          <% end %>
        <% end %>

        <blockquote>
          <p class="quote-text tweet-body"><%= tweet.body %></p>
          <% if tweet.user.provider == 'twitter' %>
            <p class="quote-source"><i class="fa fa-twitter fa-twitter-blue"></i> <%= link_to tweet.user.name + '@' + tweet.user.nickname, tweet.user.url, target: "_blank" %></a></p>
          <% elsif tweet.user.provider == 'facebook' %>
            <p class="quote-source"><i class="fa fa-facebook fa-facebook-blue"></i> <a href="https://www.facebook.com/<%= tweet.user.url %>" target="_blank"><%= tweet.user.name %></a></p>
          <% end %>
        </blockquote>
        <h4 class="date"><%= tweet.created_at.strftime("%b %d, %Y") %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/delete.js.erb
$("#product-modal").html("<%= escape_javascript(render 'delete') %>")
$("#product-modal").modal("show")

app/views/tweets/destroy.js.erb
<%= render 'save' %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', card_path(@card) %>

app/views/tweets/index.html.erb
<h1>Listing Tweets</h1>

<div id="tweets" class="transitions-enabled">
  <% @tweets.each do |tweet| %>
    <div class="box panel panel-default" style="height: 200px; width: 200px;">
      
      <div class="panel-body">
        <%= link_to image_tag(tweet.user.profile_image), tweet %>
        <%= link_to 'show', tweet_path(tweet) %>
        <p><%= tweet.body %></p>
        <p><strong><%= tweet.user.name if tweet.user %></strong></p>

        <% if current_user && tweet.user == current_user %>
          <div class="actions">
            <%= link_to edit_tweet_path(tweet) do %>
              <span class="glyphicon glyphicon-pencil"></span> Edit
            <% end %>
            <%= link_to tweet, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span> Delete
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<section id="testimonials" class="content section quote small">  
  <div class="row">
    <div class="col-sm-2 col-sm-offset-5">
      <div class="row tweets" id="tweets">
        <div class="testimonial box-shadow box">
        	<div class="display-pic">
            <%= link_to image_tag(@tweet.user.profile_image), @tweet.user.url, target: "_blank" %>
          </div>
          <div class="testimonee">
            <blockquote>
              <span class="quote-start">“</span>
              <p class="quote-text tweet-body"><%= @tweet.body %></p>
              <% if @tweet.user.provider == 'twitter' %>
                <p class="quote-source"><i class="fa fa-twitter fa-twitter-blue"></i> <%= link_to @tweet.user.name + '@' + @tweet.user.nickname, @tweet.user.url, target: "_blank" %></a></p>
              <% elsif @tweet.user.provider == 'facebook' %>
                <p class="quote-source"><i class="fa fa-facebook fa-facebook-blue"></i> <a href="https://www.facebook.com/<%= @tweet.user.url %>" target="_blank"><%= @tweet.user.name %></a></p>
              <% end %>

              <span class="quote-end">”</span>
            </blockquote>
            <p class="date"><%= @tweet.created_at.strftime("%b %d, %Y") %></p>
          </div>
          <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-message-submit' %>
          <%= link_to 'Back', card_path(@card), :class => 'btn btn-white' %>
        </div>
      </div>
    </div>
  </div>
</section> <!-- end Testimonials Section -->

app/views/tweets/show.js.erb
$("#show-tweet").html("<%= escape_javascript(render 'show') %>")
$("#show-tweet").modal("show")