config/routes.rb
Rails.application.routes.draw do
  resources :homes
  get 'create', to: 'cards#new'
  get 'mycards', to: 'cards#mycards'
  get 'admincards', to: 'cards#admincards'
  get 'alluserscards', to: 'cards#alluserscards'

  get 'login', to: 'homes#login'
  
  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap

  devise_for :admins
  resources :cards do
    resources :tweets do
      get "delete"
      member do
        put "like" => "tweets#upvote"
        put "unlike" => "tweets#downvote"
      end
    end
  end
  get '/users/auth/:provider/callback', to: 'sessions#create'
  get "users/sign_out" => "sessions#destroy", :as => :signout  
  devise_for :users
  resources :tweets
  root to: "homes#index"

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  # GET /homes
  # GET /homes.json
  def index
    @cards = Card.all
  end

  def login
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def home_params
    #   params[:home]
    # end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<div id="intro">
  <div class="item background-cover" style="background: url('../assets/home1.jpg') center center no-repeat">
    <div class="container">
      <div class="row">
        <div class="carousel-caption-center colour-white">
          <h2>Create unique online <span class="rotate handwritting">christmas , birthday , wedding , greeting </span>cards.</br>
          Sign with friends and surprise that special someone.</h2>
          <% if user_signed_in? %>
            <p><%= link_to 'Create A Free Evercard', create_path, :class => "btn btn-lg btn-primary signup" %></p>
          <% else %>
            <p><%= link_to 'Create A Free Evercard', login_path, :class => "btn btn-lg btn-primary signup" %></p>
          <% end %>
          <h4><%= link_to 'See  Nimo\'s Birthday Evercard', card_path(@cards.find(1)) %></h4>
        </div>
      </div>
    </div>
    <div class="overlay-bg"></div>
  </div>
</div>

app/views/homes/indexmj.html.erb
<!-- Hero Banner
================================================== -->

<div id="intro">
  <% card1=@cards.find(1) %>
  <div class="item background-cover" style="background: url(<%= card1.image %>)">
    <div class="container">
      <div class="row">
        <div class="carousel-caption-center colour-white">
          <h2><%= card1.hashtag %></h2>
          <h1><%= card1.name %></h1>
          <p><%= card1.description %></p>
          <p><%= link_to 'Open Card', card_path(card1), :class => 'btn btn-primary' %></p>
          <div class="photo-credits">
            <p><%= card1.copyright %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="overlay-bg"></div>
  </div>
</div>

app/views/homes/login.html.erb
<div id="intro">
  <div class="item background-cover" style="background: url('../assets/home1.jpg') center center no-repeat">
    <div class="container">
      <div class="row">
        <div class="carousel-caption-center colour-white">
          <p>
            <a href="../users/auth/twitter"><button class="btn btn-twitter btn-width twitter-login-blue" style="background-color:#4099ff; margin-bottom: 0px;"><i class="fa fa-twitter"></i> | Log In With Twitter</button></a>
            <hr class="socials-seperator">
            <a href="../users/auth/facebook"><button class="btn btn-facebook btn-width facebook-login-blue" style="background-color:#3b5998;"><i class="fa fa-facebook"></i> | Log In With Facebook</button></a>
          </p>
        </div>
      </div>
    </div>
    <div class="overlay-bg"></div>
  </div>
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>