config/routes.rb
Rails.application.routes.draw do
  resources :homes
  get 'create', to: 'cards#new'
  get 'mycards', to: 'cards#mycards'
  get 'admincards', to: 'cards#admincards'
  get 'alluserscards', to: 'cards#alluserscards'

  get 'login', to: 'homes#login'
  
  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap

  devise_for :admins
  resources :cards do
    resources :tweets do
      get "delete"
      member do
        put "like" => "tweets#upvote"
        put "unlike" => "tweets#downvote"
      end
    end
  end
  get '/users/auth/:provider/callback', to: 'sessions#create'
  get "users/sign_out" => "sessions#destroy", :as => :signout  
  devise_for :users
  resources :tweets
  root to: "homes#index"

end

app/models/card.rb
class Card < ActiveRecord::Base
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged
	after_create :remake_slug
	
	def slug_candidates
    [
      :name,
      [:name, :id],
    ]
  end

  def remake_slug
    self.update_attribute(:slug, nil)
    self.save!
  end

  #You don't necessarily need this bit, but I have it in there anyways
  def should_generate_new_friendly_id?
    new_record? || self.slug.nil?
  end

	has_many :tweets
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, :s3_protocol => :https
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:new, :create, :edit, :update, :destroy, :mycards]
  # before_action :is_admin?, only: [:new, :create]

  # GET /cards
  # GET /cards.json
  def admincards
    if user_signed_in? && current_user.admin == true
      @cards = Card.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 24)
    else
      redirect_to root_path
    end
  end

  def alluserscards
    if user_signed_in? && current_user.admin == true
      @cards = Card.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 24)
    else
      redirect_to root_path
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.friendly.find(params[:id])
    @tweets = @card.tweets.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 24)
    @card_tweet_count = @card.tweets.count

    # setting user
    card_user_id = @card.user_id
    @user = User.find(card_user_id)

    if user_signed_in?
      @user_id = current_user.id
      @user_tweets = @tweets.where(:user_id => @user_id)
      @user_tweet_count = @user_tweets.count
    end
  end
  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
    @card = Card.friendly.find(params[:id])
    redirect_to root_path, notice: 'Not authorised to update this card' if @card.user_id.to_f != current_user.id unless current_user.admin
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    if current_user.admin
      @card.admin_card = true
    end
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def mycards
    user_id = current_user.id
    @cards = Card.where(:user_id => user_id).order(created_at: :desc).paginate(:page => params[:page], :per_page => 24)
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    @card = Card.friendly.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end


  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :description, :image, :hashtag, :date)
    end

    def correct_user
      if user_signed_in?
        user_id = current_user.id
        @cards = Card.where(:user_id => user_id).order(created_at: :desc)
        redirect_to root_path, notice: 'Not authorised to update this pin' if @cards.nil? unless current_user.admin
      else
        redirect_to root_path
      end
    end

    # def is_admin?
    #   redirect_to root_path, notice: 'You\'re not authorised to do so' unless current_user.admin
    # end
  end

app/helpers/cards_helper.rb
module CardsHelper
end

#makes paperclip(media upload) validates
module Paperclip
  class MediaTypeSpoofDetector
    def spoofed?
      false
    end
  end
end

app/views/cards/_form.html.erb
<%= form_for@card, html: { multipart: true, class: 'form-horizontal' } do |f| %>
  <% if @card.errors.any? %>
  <% end %>

  <fieldset>
    <!-- Text input-->
    <div class="form-group">
      <label class="col-sm-4 control-label" for="textinput"><%= f.label :title %> *</label>  
      <div class="col-sm-4">
      <%= f.text_field :name, placeholder: "Peter McCoy", class: 'form-control input-lg', required: "" %>
      <span class="help-block">Card's title / name of the person receiving this card</span>  
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-sm-4 control-label" for="textinput"><%= f.label :hashtag %></label>  
      <div class="col-sm-4">
      <%= f.text_field :hashtag, placeholder: "#peters21st", class: 'form-control input-lg' %>
      <span class="help-block">Make it social!</span>  
      </div>
    </div>

    <!-- Text input-->
    <div class="form-group">
      <label class="col-sm-4 control-label" for="textinput"><%= f.label :date %> *</label>  
      <div class="col-sm-4">
      <%= f.text_field :date, placeholder: "21st January 2016", class: 'form-control input-lg', required: "" %>
      <span class="help-block">When's the card for?</span>  
      </div>
    </div>

    <!-- Textarea -->
    <div class="form-group">
      <label class="col-sm-4 control-label" for="textarea"><%= f.label :description %> *</label>
      <div class="col-sm-4">
        <%= f.text_area :description, class: 'form-control', id: 'textarea', rows: '3', maxlength: '150', required: ""  %>                     
        <span class="help-block" style="float:left">What's the card for?</span><div id="textarea_feedback"></div> 
      </div>
    </div>

    <!-- File Button --> 
    <div class="form-group">
      <label class="col-sm-4 control-label" for="filebutton"><%= f.label :image %> </label>
      <div class="col-sm-4">
        <%= f.file_field :image, id: 'filebutton', class: 'input-file file-button', type: 'file' %>
        <span class="help-block">Background photo for the card</span>  
      </div>
    </div>

    <!-- Text input-->
    <% if current_user.admin %>
    <div class="form-group">
      <label class="col-sm-4 control-label" for="textinput"><%= f.label :copyright %></label>  
      <div class="col-sm-4">
        <%= f.text_field :copyright, id: 'textinput', type: 'text', placeholder: 'Photo: AP Photo/Cliff Schiappa', class: 'form-control input-lg' %>
      </div>
    </div>
    <% end %>
  </fieldset>

  <div class="text-center">
    <%= f.submit 'Submit', class: 'btn btn-message-submit' %>
    <%= link_to 'Cancel', :back, :class => 'btn btn-message-submit btn-cancel-white' %>
  </div>
<% end %>

app/views/cards/admincards.html.erb
<section id="pricing" class="dark mycards-bg">

 <div class="page-header text-center">
   </br></br></br>
   <h2>Admin Evercards</h2>
 </div>

 <div class="container">
   <div class="row">
      <div class="plans">
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= link_to create_path do %>
            <div class="plan">
              <div class="plan-title"></div>
              <ul class="plan-features">
                <li style="height: 291px; background-color: #e3695c; color:white; border-bottom: 1px solid #e3695c; font-size: 22px;">Create Evercard</li>
              </ul>
            </div>
          <% end %>
        </div>

        <% @cards.each do |card| %>
          <% if card.admin_card == true %>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <%= link_to card_path(card.slug) do %>
                <div class="plan">
                  <% if !(card.image.content_type =~ /^image/).nil? %>
                    <div class="plan-title" style="background: url(<%= card.image %>) center center no-repeat; background-size:cover;"></div>
                  <% else %>
                    <div class="plan-title" style="background: url('../assets/placeholder.png') center center no-repeat; background-size:cover;"></div>
                  <% end %>
                  <ul class="plan-features">
                    <% if current_user.admin? %>
                      <li>Card ID: <%= card.id %></li>
                    <% end %> 
                    <li><%= card.name %></li>
                    <% if card.tweets.count > 0 %>
                      <li><%= card.tweets.count %> <%= "Message".pluralize(card.tweets.count) %></li>
                    <% else %>
                      <li>No Messages</li>
                    <% end %>
                    <li>Created on: <%= card.created_at.strftime("%b %d, %Y") %></li>
                    <li><%= link_to 'Delete', card, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Edit', edit_card_path(card) %></li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= will_paginate @cards, renderer: BootstrapPagination::Rails %>
  </div>
</section>

app/views/cards/alluserscards.html.erb
<section id="pricing" class="dark mycards-bg">

  <div class="page-header text-center">
    </br></br></br>
    <h2>All Users Evercards</h2>
  </div>
  <div class="container">
   <div class="row">
      <div class="plans">
        <% @cards.each do |card| %>
          <% if !card.admin_card  %>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <%= link_to card_path(card.slug) do %>
                <div class="plan">
                  <% if !(card.image.content_type =~ /^image/).nil? %>
                    <div class="plan-title" style="background: url(<%= card.image %>) center center no-repeat; background-size:cover;"></div>
                  <% else %>
                    <div class="plan-title" style="background: url('../assets/placeholder.png') center center no-repeat; background-size:cover;"></div>
                  <% end %>
                  <ul class="plan-features">
                    <% if current_user.admin? %>
                      <li>Card ID: <%= card.id %></li>
                    <% end %> 
                    <li><%= card.name %></li>
                    <% if card.tweets.count > 0 %>
                      <li><%= card.tweets.count %> <%= "Message".pluralize(card.tweets.count) %></li>
                    <% else %>
                      <li>No Messages</li>
                    <% end %>
                    <li>Created on: <%= card.created_at.strftime("%b %d, %Y") %></li>
                    <li><%= link_to 'Delete', card, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Edit', edit_card_path(card) %></li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= will_paginate @cards, renderer: BootstrapPagination::Rails %>
  </div>
</section>

app/views/cards/edit.html.erb
<section id="pricing" class="dark mycards-bg">

  <div class="page-header text-center">
    </br></br></br>
    <h2>Edit</h2>
    <p><%= @card.name %>'s Evercard</p>
  </div>

	<%= render 'form' %>

</section>

app/views/cards/mycards.html.erb
<section id="pricing" class="dark mycards-bg">

 <div class="page-header text-center">
   </br></br></br>
   <h2>My Evercards</h2>
 </div>

 	<div class="container">
   	<div class="row">
     	<div class="plans">

     		<div class="col-xs-12 col-sm-6 col-md-3">
       		<%= link_to create_path do %>
	       	  <div class="plan">
           		<div class="plan-title"></div>
	           	<ul class="plan-features">
	             	<li style="height: 234px; background-color: #e3695c; color:white; border-bottom: 1px solid #e3695c; font-size: 22px;">Create Evercard</li>
	           	</ul>
	         	</div>
	        <% end %>
       	</div>

	     		<% @cards.each do |card| %>
		       	<div class="col-xs-12 col-sm-6 col-md-3">
		       		<%= link_to card_path(card.slug) do %>
			         	<div class="plan">
			         		<% if !(card.image.content_type =~ /^image/).nil? %>
		           			<div class="plan-title" style="background: url(<%= card.image %>) center center no-repeat; background-size:cover;"></div>
		           		<% else %>
		           			<div class="plan-title" style="background: url('../assets/placeholder.png') center center no-repeat; background-size:cover;"></div>
		           		<% end %>
			           	<ul class="plan-features">
			             	<li><%= card.name %></li>
			             	<% if card.tweets.count > 0 %>
			             		<li><%= card.tweets.count %> <%= "Message".pluralize(card.tweets.count) %></li>
			             	<% else %>
			             		<li>No Messages</li>
			             	<% end %>
			             	<li>Created on: <%= card.created_at.strftime("%b %d, %Y") %></li>
			             	<li><%= link_to 'Delete', card, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Edit', edit_card_path(card) %></li>
			           	</ul>
			         	</div>
		         	<% end %>
		         	<div>
		         	
		         	</div>
	       		</div>
	       	<% end %>
     	</div>
		</div>
		<%= will_paginate @cards, renderer: BootstrapPagination::Rails %>
	</div>
</section>

app/views/cards/new.html.erb
<section id="pricing" class="dark mycards-bg">

  <div class="page-header text-center">
    </br></br></br>
    <h2>Create Evercard</h2>
  </div>

	<%= render 'form' %>

</section>

app/views/cards/show.html.erb
<% if !(@card.image.content_type =~ /^image/).nil? %>
<section id="about" class="content text-center light" style="background: url(<%= @card.image %>) center center no-repeat; background-size:cover;">
<% else %>
<section id="about" class="content text-center dark with-bg">
<% end %> 

  <br><br><br><br><br>
  <div class="container">
    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-12 overlay-text white">
        <h2 class="shadow"><%= @card.name %></h2>
        <p class="card-description" style="color: rgba(255, 255, 255, 0.6);"><%= @card.description %></p>

        <% if @card.hashtag.length > 0 %>
          <h4 class="card-info"><%= @card.hashtag %> | <%= @card.date %></br>
        <% else %>
          <h4 class="card-info"><%= @card.date %></br>
        <% end %> 
            Created by 
            <% if @user.provider == 'twitter' %>
              <%= link_to @user.name, @user.url, target: "_blank" %>
            <% elsif @user.provider == 'facebook' %>
              <%= link_to @user.name, "https://www.facebook.com/" + @user.url, target: "_blank" %>
            <% end %>
          </h4>

        <% if @card_tweet_count > 0 %>
          <h3 class="shadow"><%= @card_tweet_count %> <%= "Message".pluralize(@card_tweet_count) %></h3>
        <% end %>
        
        <% if user_signed_in? %>
          <% if @user_tweet_count > 0 %>
            <% if current_user.admin == false %>
              <% @user_tweets.each do |tweet| %>
                <p><%= link_to 'My Message', card_tweet_path(@card,tweet.id), remote: true, :class => 'btn btn-message-submit' %></p>
              <% end %>
            <% end %> 
          <% else %>
            <br>
            <% if @card_tweet_count > 0 %>
              <h4>Your Message</h4>
              <%= form_for([@card, @card.tweets.build]) do |f| %>
                <h4><%= f.text_area :body %></h4>
                <p><%= f.submit 'Submit', :class => 'btn btn-message-submit' %></p>
              <% end %>
            <% else %>
              <h4>Be The First!</h4>
              <%= form_for([@card, @card.tweets.build]) do |f| %>
                <h4><%= f.text_area :body %></h4>
                <p><%= f.submit 'Submit', :class => 'btn btn-message-submit' %></p>
              <% end %>
            <% end %>
          <% end %>
        <% else %>
          <p>
            <a href="../users/auth/twitter"><button class="btn btn-twitter twitter-blue btn-width"><i class="fa fa-twitter"></i> | Tweet Your Message</button></a> <a href="../users/auth/facebook"><button class="btn btn-facebook facebook-blue btn-width"><i class="fa fa-facebook"></i> | Post Your Message</button></a>
          </p>
        <% end %>
      </div><!-- /.col-lg-12 -->
    </div><!-- /.row -->
  </div>

  <% if !(@card.image.content_type =~ /^image/).nil? %>
  <div class="overlay-bg2"></div>
  <% else %>
  <div class="overlay-bg3"></div>
  <% end %>

</section>


<% if @card.tweets %>
  <section id="testimonials" class="content section quote small">  
    <div class="row">
      <div class="col-lg-12">
        <div id="posts" class="product-index">
          <%= render 'tweets/tweets' %>
        </div>
        <div id="product-modal" class="modal fade"></div>
        <div id="show-tweet" class="modal fade"></div>
      </div>
    </div>

    <%= javascript_tag do %>
      <% if current_user && current_user.admin == true %>
        isadminuser = 'yes'
      <% else %>
        isadminuser = 'no'
      <% end %>
    <% end %>

    <% if current_user && current_user.admin == true %>
      <%= will_paginate @tweets %>
    <% else %>
      <div class="pagination-hidden">
        <%= will_paginate @tweets %>
      </div>
    <% end %>

  </section> <!-- end Testimonials Section -->
<% end %>

app/views/cards/show.js.erb
$('#posts').append("<%= escape_javascript(render 'tweets/tweets') %>").masonry({
    itemSelector: '.box'
  });


<% if @tweets.next_page %>
   $('.pagination').replaceWith('<%= escape_javascript will_paginate(@tweets) %>');
<% else %>
   // $('.pagination').replaceWith("<h1>End of Card</h1>");
   $('.pagination').replaceWith();
<% end %>