config/routes.rb
Rails.application.routes.draw do
  resources :homes
  get 'create', to: 'cards#new'
  get 'mycards', to: 'cards#mycards'
  get 'admincards', to: 'cards#admincards'
  get 'alluserscards', to: 'cards#alluserscards'

  get 'login', to: 'homes#login'
  
  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap

  devise_for :admins
  resources :cards do
    resources :tweets do
      get "delete"
      member do
        put "like" => "tweets#upvote"
        put "unlike" => "tweets#downvote"
      end
    end
  end
  get '/users/auth/:provider/callback', to: 'sessions#create'
  get "users/sign_out" => "sessions#destroy", :as => :signout  
  devise_for :users
  resources :tweets
  root to: "homes#index"

end

app/views/layouts/_navbar.html.erb
<!-- NAVBAR
================================================== -->
<div class="navbar-wrapper cbp-af-header">
  <div class="container">

    <!-- Fixed navbar -->
    <div class="navbar cbp-af-inner" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1><a class="navbar-brand scroll" href="/">evercard</a></h1>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
          	
            <% if current_user == nil %>
              <li><%= link_to 'Log In', login_path %></li>
              <li><%= link_to 'Create Evercard', login_path %></li>
            <% end %>

            <% if current_user %>
              <% if current_user.admin %>
                <li><%= link_to 'Admin Evercards', admincards_path %></li>
                <li><%= link_to 'Users Evercards', alluserscards_path %></li>
              <% else %>
                <li><%= link_to 'My Evercards', mycards_path %></li>
                <li><%= link_to 'New Evercard', new_card_path %></li>
              <% end %>
			        <li><%= link_to 'Sign Out', destroy_user_session_path %></li>
              <% if current_user.admin %>
                <li><%= link_to 'Admin Create', new_card_path %></li>
              <% end %>
           	<% end %>

            <li><a href="https://twitter.com/evercardco" target="_blank"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://www.facebook.com/evercardco/" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="mailto:hello.evercard@gmail.com" target="_blank"><i class="fa fa-envelope"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evercard</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://s3.amazonaws.com/evercard4/assets/favico/evercard_ico.png">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    
    <meta name="google-site-verification" content="fSbIY8PBJMqMxbMZrZtjz6i07sDrkPJrVON7KLZW0_c" />
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <%= yield %>

    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/bootstrap.min.js"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/classie.js"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/cbpAnimatedHeader.min.js"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/owl.carousel.min.js"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/scrollReveal.js"></script>

    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/jquery.nav.js" defer="defer"></script>

    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/imagesloaded.pkgd.min.js" defer="defer"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/isotope.min.js" defer="defer"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/jquery.magnific-popup.min.js" defer="defer"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/jqBootstrapValidation.js" defer="defer"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/less-1.6.1.min.js"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/modernizr.custom.js"></script>
    <script src="https://s3.amazonaws.com/evercard-dev/assets/javascripts/jquery.simple-text-rotator.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-70794782-1', 'auto');
      ga('send', 'pageview');

    </script>
    
    <script>
      $(document).ready(function(){
        isotope();
        signupOverlay();
        loginOverlay();

        $('.theme-option').click(function(event){
            event.preventDefault();
            less.modifyVars({
                '@theme-cta': $(this).attr('data-theme')
            });

            less.refreshStyles();
        });

      });
    </script>

    <script>
      $(".rotate").textrotator({
          animation: "dissolve",
          separator: ",",
      speed: 2500
      });
    </script>

    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  </body>
</html>